[package]
name = "sieve_of_eratosthenes"
version = "0.1.0"
authors = ["Quinn Blenkinsop <quinn@blenkinsop.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
